### ISSUE TITLE
need to add @astrojs/markdown-remark to package.json dependencies

### ISSUE THREAD

**Issue by dougouverson** [thiloho/aurora#1]
Got error "Cannot find module '@astrojs/markdown-remark'"

I added @astrojs/markdown-remark and all went well.

**Comment by thiloho** [comment]
Hey, thank you for the information.

That is awkward, normally an import as found in `astro.config.ts` should be sufficient, on my end there were no such problems. Anyways, I added `@astrojs/markdown-remark` as a dependency to the `package.json` file, so there should be no further issues. :+1:
